# Generated by Django 3.0.2 on 2020-01-17 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_h1', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('read_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approval', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('approval_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_user', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='article', to='core.Category')),
                ('slug', models.SlugField(unique=True, max_length=150, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
